terminal_width = 102
terminal_height = 54
base_layout = "sidebar"

[[windows]]
name = "main"
widget_type = "text"
streams = ["main"]
row = 0
col = 19
rows = 43
cols = 85
buffer_size = 10000
show_border = true
border_color = "-"
background_color = "-"
bar_color = "-"
bar_background_color = "-"
transparent_background = true
locked = false
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
text_color = "-"
compass_active_color = "-"
compass_inactive_color = "-"
numbers_only = false

[[windows]]
name = "command_input"
widget_type = "command_input"
streams = []
row = 53
col = 19
rows = 1
cols = 83
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
content_align = "center"
background_color = "#350505"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 3
min_cols = 20
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "compass"
widget_type = "compass"
streams = []
row = 51
col = 11
rows = 3
cols = 7
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Exits"
content_align = "center"
background_color = "-"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
max_rows = 3
min_cols = 7
max_cols = 7
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "injuries"
widget_type = "injury_doll"
streams = []
row = 48
col = 0
rows = 6
cols = 8
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Injuries"
content_align = "center-left"
background_color = "-"
bar_color = "-"
bar_background_color = "-"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "-"
compass_active_color = "-"
compass_inactive_color = "-"
min_rows = 6
max_rows = 6
min_cols = 8
max_cols = 8
numbers_only = false
injury_default_color = "#333333"
injury1_color = "#aa5500"
injury2_color = "#ff8800"
injury3_color = "#ff0000"
scar1_color = "#999999"
scar2_color = "#777777"
scar3_color = "#555555"

[[windows]]
name = "casttime"
widget_type = "countdown"
streams = []
row = 49
col = 11
rows = 1
cols = 6
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Cast"
content_align = "center"
background_color = "-"
bar_color = "#0000ff"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 6
max_cols = 6
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "stuntime"
widget_type = "countdown"
streams = []
row = 48
col = 11
rows = 1
cols = 6
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Stun"
content_align = "center"
background_color = "-"
bar_color = "#ffff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 6
max_cols = 6
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "roundtime"
widget_type = "countdown"
streams = []
row = 50
col = 11
rows = 1
cols = 7
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "RT"
content_align = "center"
background_color = "#000000"
bar_color = "#ff0000"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 7
max_cols = 7
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "spellhand"
widget_type = "spellhand"
streams = []
row = 52
col = 74
rows = 1
cols = 28
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
border_sides = [
    "left",
    "right",
]
title = "Spell"
content_align = "center"
background_color = "-"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
hand_icon = "S:"
text_color = "#666666"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "lefthand"
widget_type = "lefthand"
streams = []
row = 52
col = 19
rows = 1
cols = 27
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
border_sides = ["left"]
title = "Left Hand"
content_align = "center"
background_color = "-"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
hand_icon = "L:"
text_color = "#909090"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "righthand"
widget_type = "righthand"
streams = []
row = 52
col = 46
rows = 1
cols = 28
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
border_sides = ["left"]
title = "Right Hand"
content_align = "center"
background_color = "-"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
hand_icon = "R:"
text_color = "#666666"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "health"
widget_type = "progress"
streams = []
row = 47
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Health"
content_align = "center"
background_color = "#000000"
bar_color = "#6e0202"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "mana"
widget_type = "progress"
streams = []
row = 46
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Mana"
content_align = "center"
background_color = "-"
bar_color = "#08086d"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "stamina"
widget_type = "progress"
streams = []
row = 45
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Stamina"
content_align = "center"
background_color = "-"
bar_color = "#bd7b00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "spirit"
widget_type = "progress"
streams = []
row = 44
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Spirit"
content_align = "center"
background_color = "-"
bar_color = "#6e727c"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "encumlevel"
widget_type = "progress"
streams = []
row = 42
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Encumbrance"
content_align = "center"
background_color = "-"
bar_color = "#006400"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "pbarStance"
widget_type = "progress"
streams = []
row = 43
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Stance"
content_align = "center"
background_color = "#000000"
bar_color = "#000080"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "mindState"
widget_type = "progress"
streams = []
row = 41
col = 0
rows = 1
cols = 19
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Mind"
content_align = "center"
background_color = "-"
bar_color = "#008b8b"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 1
max_rows = 1
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "status_dashboard"
widget_type = "dashboard"
streams = []
row = 49
col = 9
rows = 6
cols = 1
buffer_size = 100
show_border = false
border_style = "single"
border_color = "#808080"
title = "Status"
content_align = "center"
background_color = "-"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "vertical"
dashboard_spacing = 0
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
numbers_only = false
effect_default_color = "#ffffff"

[[windows.dashboard_indicators]]
id = "poisoned"
icon = ""
colors = [
    "#000000",
    "#00ff00",
]

[[windows.dashboard_indicators]]
id = "diseased"
icon = ""
colors = [
    "#000000",
    "#8b4513",
]

[[windows.dashboard_indicators]]
id = "bleeding"
icon = ""
colors = [
    "#000000",
    "#ff0000",
]

[[windows.dashboard_indicators]]
id = "stunned"
icon = ""
colors = [
    "#000000",
    "#ffff00",
]

[[windows.dashboard_indicators]]
id = "webbed"
icon = "󰯊"
colors = [
    "#000000",
    "#cccccc",
]

[[windows]]
name = "players"
widget_type = "entity"
streams = [
    "playercount",
    "playerlist",
]
row = 36
col = 0
rows = 3
cols = 19
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
title = "Players"
content_align = "top-left"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "targets"
widget_type = "entity"
streams = [
    "targetcount",
    "combat",
]
row = 31
col = 0
rows = 5
cols = 19
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
title = "Targets"
content_align = "top-left"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "debuffs"
widget_type = "active_effects"
streams = []
row = 26
col = 0
rows = 5
cols = 19
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
title = "Debuffs"
content_align = "top-left"
background_color = "-"
bar_color = "#FF4040"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
visible_count = 3
effect_category = "Debuffs"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "cooldowns"
widget_type = "active_effects"
streams = []
row = 19
col = 0
rows = 7
cols = 19
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
title = "Cooldowns"
content_align = "top-left"
background_color = "-"
bar_color = "#FFB040"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
visible_count = 5
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "buffs"
widget_type = "active_effects"
streams = []
row = 9
col = 0
rows = 10
cols = 19
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
title = "Buffs"
content_align = "top-left"
background_color = "#"
bar_color = "#40FF40"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
visible_count = 8
effect_category = "Buffs"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 2
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "active_spells"
widget_type = "active_effects"
streams = []
row = 0
col = 0
rows = 9
cols = 19
buffer_size = 100
show_border = true
border_style = "single"
border_color = "#808080"
title = "Active Spells"
content_align = "top-left"
background_color = "-"
bar_color = "#4080FF"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "ActiveSpells"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
min_rows = 3
min_cols = 19
max_cols = 19
numbers_only = false
effect_default_color = "#ffffff"

[[windows]]
name = "chat"
widget_type = "tabbed"
streams = []
row = 43
col = 19
rows = 9
cols = 85
buffer_size = 5000
show_border = false
border_color = "#808080"
content_align = "top-left"
background_color = "#000000"
bar_color = "#00ff00"
bar_background_color = "#333333"
transparent_background = true
locked = false
dashboard_layout = "horizontal"
dashboard_hide_inactive = false
effect_category = "Cooldowns"
tab_bar_position = "top"
tab_active_color = "-"
tab_inactive_color = "-"
tab_unread_color = "-"
tab_unread_prefix = "* "
text_color = "#ffffff"
compass_active_color = "#00ff00"
compass_inactive_color = "#333333"
numbers_only = false
effect_default_color = "#ffffff"

[[windows.tabs]]
name = "Thoughts"
stream = "thoughts"

[[windows.tabs]]
name = "Speech"
stream = "speech"

[[windows.tabs]]
name = "Announcements"
stream = "announcements"

[[windows.tabs]]
name = "Loot"
stream = "loot"

[[windows.tabs]]
name = "Ambients"
stream = "ambients"
